apiVersion: apps/v1
kind: Deployment
metadata:
  name: solarops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solarops
  template:
    metadata:
      labels:
        app: solarops
    spec:
      containers:
      - name: solarops
        image: solarops:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000